name: Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        name: Build and test for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        env:
            PLAYWRIGHT_BROWSERS_PATH: 0

        strategy:
            fail-fast: false
            matrix:
                node-version: [ 14.x ]
                os: [ ubuntu-latest ]

        steps:
        -   uses: actions/checkout@v2
        -   name: Use Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
                node-version: ${{ matrix.node-version }}
        -   name: Install Dependencies
            run: npm install

        -   name: Run Build
            run: npm run build

        -   uses: JS-DevTools/npm-publish@v1
            with:
                token: ${{ secrets.NPM_AUTH_TOKEN }}
                check-version: false
